from __future__ import annotations

import argparse
import re
from datetime import datetime, timezone
from pathlib import Path


def resolve_project_path(project_root: Path, raw_path: str) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path.resolve()
    return (project_root / path).resolve()


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    for enc in ("utf-8", "utf-8-sig", "cp1251"):
        try:
            return path.read_text(encoding=enc)
        except UnicodeDecodeError:
            continue
        except OSError:
            return ""
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def parse_master_plan_statuses(master_plan_path: Path) -> tuple[int, int, int]:
    text = read_text(master_plan_path)
    if not text.strip():
        return 0, 0, 0

    done = len(re.findall(r"\bdone\b", text, flags=re.IGNORECASE))
    in_progress = len(re.findall(r"\bin_progress\b", text, flags=re.IGNORECASE))
    todo = len(re.findall(r"\btodo\b", text, flags=re.IGNORECASE))
    return done, in_progress, todo


def extract_recent_tools(payload_log_path: Path, limit: int = 12) -> list[str]:
    text = read_text(payload_log_path)
    if not text.strip():
        return []
    tools = re.findall(r"^tool:\s*(.+?)\s*$", text, flags=re.MULTILINE)
    if not tools:
        return []
    return tools[-limit:]


def build_report(
    *,
    project_root: Path,
    memory_dir: Path,
    tasks_dir: Path,
    run_id: str,
    status: str,
) -> str:
    master_plan_path = tasks_dir / "master_plan.md"
    payload_log_path = memory_dir / "logs" / "cloud_payload_audit.md"

    done, in_progress, todo = parse_master_plan_statuses(master_plan_path)
    recent_tools = extract_recent_tools(payload_log_path)

    rows = [
        "# Orchestrator Memory Call Checklist (Current Run)",
        "",
        "This file is overwritten on each orchestrator closure run.",
        "",
        "## META",
        f"- generated_at: {utc_now()}",
        f"- run_id: {run_id}",
        f"- status: {status}",
        f"- project_root: {project_root.as_posix()}",
        f"- memory_dir: {memory_dir.as_posix()}",
        f"- tasks_dir: {tasks_dir.as_posix()}",
        "",
        "## Memory Call Checklist",
        f"- local_memory_bootstrap observed: {'yes' if 'local_memory_bootstrap' in recent_tools else 'no'}",
        f"- local_memory_brief observed: {'yes' if 'local_memory_brief' in recent_tools else 'no'}",
        f"- get_memory_metadata observed: {'yes' if 'get_memory_metadata' in recent_tools else 'no'}",
        f"- consolidate_memory observed: {'yes' if 'consolidate_memory' in recent_tools else 'no'}",
        "",
        "## Task Status Snapshot",
        f"- done markers: {done}",
        f"- in_progress markers: {in_progress}",
        f"- todo markers: {todo}",
        "",
        "## Recent Cloud-Payload Tools",
    ]

    if recent_tools:
        rows.extend([f"- {tool}" for tool in recent_tools])
    else:
        rows.append("- none observed")

    rows.extend(
        [
            "",
            "## Generation Guarantee",
            "- Generated by deterministic local Python script.",
            "- No local LLM or cloud LLM calls are used for this report.",
            "",
        ]
    )

    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Write orchestrator memory-call checklist for a specific orchestration run."
    )
    parser.add_argument("--project-root", required=True, help="Project root path")
    parser.add_argument("--memory-dir", default="memory", help="Memory dir relative to project root")
    parser.add_argument(
        "--tasks-dir",
        default=".vscode/tasks",
        help="Run-specific orchestration artifacts directory relative to project root",
    )
    parser.add_argument("--run-id", default="orchestrator_run", help="Run identifier")
    parser.add_argument("--status", default="completed", help="Run status (completed/failed/halted)")
    parser.add_argument(
        "--output",
        default="",
        help="Optional explicit checklist output path; defaults to memory/logs/orchestrator_memory_checklist_<run_id>.md",
    )
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    memory_dir = resolve_project_path(project_root, args.memory_dir)
    tasks_dir = resolve_project_path(project_root, args.tasks_dir)
    out_path = resolve_project_path(project_root, args.output) if args.output else (memory_dir / "logs" / f"orchestrator_memory_checklist_{args.run_id}.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    report = build_report(
        project_root=project_root,
        memory_dir=memory_dir,
        tasks_dir=tasks_dir,
        run_id=args.run_id,
        status=args.status,
    )
    out_path.write_text(report, encoding="utf-8")

    print("[orchestrator-checklist] written")
    print(f"output={out_path.as_posix()}")
    print(f"run_id={args.run_id}")
    print(f"status={args.status}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
